import React, { useState } from "react";
import { AlertTriangle, ArrowRight, BriefcaseBusiness, CalendarDays, Check, ChevronLeft, ChevronRight, CircleDollarSign, Clock3, Download, ExternalLink, FileText, Flag, ListChecks, Plus, RefreshCw, Sparkles, Tag, Target, Trash2, TrendingUp, UserRound, UsersRound, X } from "lucide-react";
import { api } from "./api";
import SearchableSelect, { AdaptiveSelect } from "./SearchableSelect";
import "./podResourcing.css";

const DAY = 86400000;
const monday = (date) => { const d = new Date(date); const n = (d.getDay()+6)%7; d.setDate(d.getDate()-n); d.setHours(0,0,0,0); return d; };
const monthStart = (date) => new Date(date.getFullYear(), date.getMonth(), 1);
const money = (v) => `$${(v/1000000).toFixed(1)}M`;
const shortDate = (d) => d.toLocaleDateString("en-US", {month:"short",day:"numeric"});
const longMonth = (d) => d.toLocaleDateString("en-US", {month:"long",year:"numeric"});
const time = (v) => new Date(v).toLocaleTimeString("en-US", {hour:"numeric",minute:"2-digit"});
const initials = (name) => name.split(" ").map(x=>x[0]).slice(0,2).join("");
const todayKey = () => { const value=new Date(); return `${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,"0")}-${String(value.getDate()).padStart(2,"0")}`; };
const emptyDashboard = () => ({people:[],meetings:[],upcomingPrep:[],opportunities:[],criticalItems:[],tasks:[],relationships:[],relationshipAttention:[],milestones:[],commitments:[],focus:[],health:[],tagOptions:[],activeTag:"All",summary:{meetingCount:0,buyerCount:0,influencerCount:0,deadlineCount:0,urgentDeadlineCount:0,openActionCount:0,overdueActionCount:0,pipelineValue:0,weightedPipelineValue:0,relationshipAttentionCount:0,highRelationshipAttentionCount:0}});
const TagList = ({tags=[]}) => tags.length ? <span className="record-tags">{tags.slice(0,4).map(value=><i key={value}>{value}</i>)}</span> : null;

function Section({title, meta, action, className="", children}) { return <section className={`pod-card ${className}`}><header><div><h2>{title}</h2>{meta&&<span>{meta}</span>}</div>{action}</header>{children}</section>; }
function EmptyState({children}) { return <div className="pod-empty"><ListChecks/><span>{children}</span></div>; }
function CommitmentList({items,pod,onPerson,onResolve,canWrite}) { return <div className="commitment-list">{!items.length&&<EmptyState>No upcoming deadlines match this filter</EmptyState>}{items.map(item=>{const when=new Date(`${item.deadline}T12:00:00`);const resolvable=canWrite&&item.sourceType==="critical";return <article key={`${item.pod}-${item.sourceType}-${item.id}`} className={item.priority.toLowerCase()}><span><b>{when.getDate()}</b><small>{when.toLocaleDateString("en-US",{month:"short"}).toUpperCase()}</small></span><div><em>{item.priority} · {item.category}</em><b>{item.title}</b><small>Due {when.toLocaleDateString("en-US",{month:"short",day:"numeric"})} · {item.owner}{item.stakeholder?` · ${item.stakeholder}`:""}{pod==="All"?` · ${item.pod}`:""}</small><TagList tags={item.tags}/></div><span className="commitment-actions">{resolvable&&<button className="resolve" onClick={()=>onResolve(item)} title="Resolve deadline"><Check/></button>}{item.stakeholderId&&<button onClick={()=>onPerson({id:item.stakeholderId})} title="Open stakeholder"><ChevronRight/></button>}</span></article>})}</div>; }

function RelationshipAttention({items,pod,onPerson}) { return <div id="pod-relationships" className="relationship-list">{!items.length&&<EmptyState>No relationships need attention</EmptyState>}{items.map(item=><button key={`${item.pod}-${item.stakeholderId}`} onClick={()=>onPerson({id:item.stakeholderId,name:item.stakeholder})} title={item.contextSignal||item.recencySource}><span className="relationship-avatar">{initials(item.stakeholder)}</span><span><b>{item.stakeholder}</b><small>{item.title}{pod==="All"?` · ${item.pod}`:""}</small><em>{item.signal}</em><TagList tags={item.tags}/></span><span><strong>{item.days==null?"Never":`${item.days}d`}</strong><small>{item.lastMeeting?`last met ${new Date(`${item.lastMeeting}T12:00:00`).toLocaleDateString("en-US",{month:"short",day:"numeric"})}`:"no meeting recorded"}</small><i className={`relationship-trend ${item.trend?.toLowerCase().replace(" ","-")}`}>{item.trend}</i></span><ChevronRight/></button>)}</div>; }

function layoutCalendarEvents(events) {
  const sorted=[...events].sort((a,b)=>new Date(a.start)-new Date(b.start));
  const clusters=[]; let cluster=[]; let clusterEnd=0;
  const closeCluster=()=>{if(!cluster.length)return;const laneEnds=[];const assigned=cluster.map(event=>{const start=new Date(event.start).getTime();let lane=laneEnds.findIndex(end=>end<=start);if(lane<0)lane=laneEnds.length;laneEnds[lane]=new Date(event.end).getTime();return{event,lane}});assigned.forEach(item=>clusters.push({...item,laneCount:laneEnds.length}));cluster=[];clusterEnd=0};
  sorted.forEach(event=>{const start=new Date(event.start).getTime(),end=new Date(event.end).getTime();if(cluster.length&&start>=clusterEnd)closeCluster();cluster.push(event);clusterEnd=Math.max(clusterEnd,end)});closeCluster();return clusters;
}

function WeekCalendar({anchor, events, filter, onEvent}) {
  const start=monday(anchor); const days=Array.from({length:5},(_,i)=>new Date(start.getTime()+i*DAY));
  const visible=events.filter(e=>filter==="All" || (filter==="Client"&&["client","workshop","critical"].includes(e.type)) || (filter==="Internal"&&e.type==="internal") || (filter==="Deadlines"&&e.type==="deadline"));
  return <div className="week-calendar"><div className="week-hours"><span>ET</span>{[8,10,12,14,16,18,20].map(h=><span key={h}>{h>12?h-12:h}:00</span>)}</div>{days.map(day=>{const dayEvents=layoutCalendarEvents(visible.filter(e=>new Date(e.start).toDateString()===day.toDateString()));return <div className="week-day" key={day.toISOString()}><div className={`day-head ${day.toDateString()===new Date().toDateString()?"today":""}`}><b>{day.toLocaleDateString("en-US",{weekday:"short"}).toUpperCase()}</b><span>{day.getDate()}</span><small>{dayEvents.length}</small></div><div className="day-track">{dayEvents.map(({event:e,lane,laneCount})=>{const d=new Date(e.start); const top=Math.max(0,Math.min(96,((d.getHours()+d.getMinutes()/60)-8)/12*100));return <button key={`${e.pod}-${e.id}`} style={{top:`${top}%`,left:`calc(${lane/laneCount*100}% + 3px)`,width:`calc(${100/laneCount}% - 6px)`,right:"auto"}} className={`calendar-event ${e.type} ${laneCount>1?"compact":""}`} onClick={()=>onEvent(e)} title={`${time(e.start)} · ${e.title} · ${e.person} · ${e.pod} · Capco: ${(e.capcoAttendees||[]).join(", ")}`}><b>{time(e.start)}</b><strong>{e.title}</strong><span>{e.person}</span><small>{e.pod}</small><i>AI</i></button>})}</div></div>})}</div>;
}

function MonthCalendar({anchor, events, milestones, onEvent, onDay}) {
  const first=monthStart(anchor); const gridStart=monday(first); const cells=Array.from({length:42},(_,i)=>new Date(gridStart.getTime()+i*DAY));
  return <div className="month-calendar"><div className="month-weekdays">{["MON","TUE","WED","THU","FRI","SAT","SUN"].map(x=><span key={x}>{x}</span>)}</div><div className="month-grid">{cells.map(day=>{const items=events.filter(e=>new Date(e.start).toDateString()===day.toDateString()); const ms=milestones.filter(m=>m.date===shortDate(day)); return <button key={day.toISOString()} className={`${day.getMonth()!==anchor.getMonth()?"outside":""} ${day.toDateString()===new Date().toDateString()?"today":""}`} onClick={()=>onDay({day,items,milestones:ms})}><b>{day.getDate()}</b>{items.length>0&&<span className="month-count">{items.length} meeting{items.length>1?"s":""}</span>}{items.slice(0,2).map(e=><i className={e.type} key={`${e.pod}-${e.id}`} onClick={(x)=>{x.stopPropagation();onEvent(e)}}>{time(e.start)} · {e.title}</i>)}{items.length>2&&<span className="month-more">+{items.length-2} more · open day</span>}{ms.slice(0,1).map(m=><i className="milestone" key={m.title}><Flag /> {m.title}</i>)}</button>})}</div></div>;
}

function MeetingDrawer({event, people, opportunity, canWrite, onClose, onStakeholder, onOpportunity}) {
  const person=people.find(p=>p.id===event.stakeholderId)||people.find(p=>p.name===event.person);
  const attendees=event.capcoAttendees||[]; const [copied,setCopied]=useState(false);
  const meetingId=event.meetingId||event.id; const [documents,setDocuments]=useState([]); const [uploadOpen,setUploadOpen]=useState(false); const [saving,setSaving]=useState(false); const [documentError,setDocumentError]=useState("");
  const [brief,setBrief]=useState(null); const [briefLoading,setBriefLoading]=useState(true); const [briefError,setBriefError]=useState("");
  const [document,setDocument]=useState({title:`${event.title} document`,file:null,sharepoint_url:"",document_type:"Meeting Brief",description:"",owner:attendees[0]||"Capco Account Team",tags:(event.tags||[]).join(", ")});
  const loadDocuments=()=>api.getMeetingDocuments(meetingId).then(setDocuments).catch(()=>setDocumentError("Meeting documents could not be loaded."));
  const loadBrief=async()=>{setBriefLoading(true);setBriefError("");try{setBrief(await api.getMeetingBrief(meetingId))}catch(error){setBriefError(error.message||"The meeting brief could not be generated.")}finally{setBriefLoading(false)}};
  React.useEffect(()=>{loadDocuments();loadBrief()},[meetingId]);
  const uploadDocument=async(e)=>{e.preventDefault();if(!canWrite||!document.file)return;setSaving(true);setDocumentError("");try{await api.uploadMeetingDocument(meetingId,document.file,{title:document.title,sharepoint_url:document.sharepoint_url,document_type:document.document_type,description:document.description,owner:document.owner,tags:document.tags});await loadDocuments();setUploadOpen(false);setDocument({...document,file:null,sharepoint_url:"",description:""})}catch(error){setDocumentError(error.message)}finally{setSaving(false)}};
  const removeDocument=async(id)=>{if(!canWrite||!window.confirm("Remove this meeting document and its stored file? This cannot be undone."))return;setSaving(true);setDocumentError("");try{await api.deleteDocument(id);await loadDocuments()}catch(error){setDocumentError(error.message)}finally{setSaving(false)}};
  const copyBrief=async()=>{const content=brief?`${brief.meeting.title}\n${brief.executiveSummary}\n\nObjectives\n${brief.objectives.map(value=>`- ${value}`).join("\n")}\n\nOpen actions\n${brief.openActions.map(value=>`- ${value}`).join("\n")}\n\nRecommended questions\n${brief.recommendedQuestions.map(value=>`- ${value}`).join("\n")}`:`${event.title}\n${event.person} · ${event.unit}\nCapco: ${attendees.join(", ")}\nOpen actions: ${(event.openActions||[]).join("; ")}`;try{await navigator.clipboard.writeText(content);setCopied(true)}catch{setCopied(false)}};
  return <div className="pod-drawer-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><aside className="pod-detail meeting-detail" role="dialog" aria-modal="true" aria-label={`${event.title} meeting intelligence`}><button className="pod-detail-close" onClick={onClose} aria-label="Close"><X/></button><div className="detail-kicker"><CalendarDays/> MEETING INTELLIGENCE</div><h2>{event.title}</h2><p className="detail-time">{new Date(event.start).toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric"})} · {time(event.start)}–{time(event.end)}</p>{person?<><div className="meeting-person"><span>{initials(person.name)}</span><div><b>{person.name}</b><small>{person.title} · {person.unit}</small><em>{person.role}</em></div></div><dl><dt>Relationship</dt><dd>{person.relationship}</dd><dt>Last engagement</dt><dd>{person.lastMeeting?new Date(`${person.lastMeeting}T12:00:00`).toLocaleDateString("en-US",{month:"long",day:"numeric",year:"numeric"}):"Not recorded"}</dd></dl></>:<div className="internal-note">Internal Capco working session</div>}
    <h3>Capco attendees</h3><div className="attendee-list">{attendees.length?attendees.map(name=><span key={name}><UserRound/>{name}</span>):<small>No attendees assigned</small>}</div>
    <section className="ai-meeting-brief"><header><div><Sparkles/><span><b>AI meeting brief</b><small>Grounded in live account records</small></span></div><button onClick={loadBrief} disabled={briefLoading} title="Regenerate from current data"><RefreshCw/> Regenerate</button></header>{briefLoading?<div className="brief-loading"><Sparkles/><span>Reading linked documents, notes, actions, and stakeholder context…</span></div>:briefError?<p className="modal-error">{briefError}</p>:brief&&<><p className="brief-summary">{brief.executiveSummary}</p><div className="brief-source-counts"><span>{brief.sourceSummary.meetingDocuments+brief.sourceSummary.stakeholderDocuments} documents</span><span>{brief.sourceSummary.stakeholderNotes} notes</span><span>{brief.sourceSummary.priorMeetings} prior meetings</span><span>{brief.sourceSummary.activeRisks} risks</span></div><div className="brief-columns"><div><h3>Meeting objectives</h3><ul>{brief.objectives.slice(0,4).map(value=><li key={value}>{value}</li>)}</ul></div><div><h3>Recommended questions</h3><ul>{brief.recommendedQuestions.slice(0,4).map(value=><li key={value}>{value}</li>)}</ul></div></div>{brief.latestIntelligence.length>0&&<div className="brief-intelligence"><h3>Latest grounded intelligence</h3>{brief.latestIntelligence.slice(0,3).map((item,index)=><article key={`${item.type}-${index}`}><span>{item.type}</span><p>{item.text}</p></article>)}</div>}</>}</section>
    <div className="prep-block"><h3>Previous engagement</h3><p>{event.previousEngagement||"No previous engagement summary is available."}</p></div>
    {opportunity&&<button className="commercial-context" onClick={()=>onOpportunity(opportunity)}><span>COMMERCIAL CONTEXT</span><b>{opportunity.name}</b><p>{money(opportunity.value)} · {opportunity.probability}% · {opportunity.stage}</p><ArrowRight/></button>}
    <h3>Open actions</h3><ul>{(event.openActions||["Confirm outstanding actions and decision required."]).map(item=><li key={item}>{item}</li>)}</ul><h3>Suggested discussion topics</h3><ul>{(event.discussionTopics||["Decision timing","Commercial next step"]).map(item=><li key={item}>{item}</li>)}</ul>
    <div className="meeting-documents"><div className="section-title"><h3>Meeting documents</h3>{canWrite&&<button onClick={()=>setUploadOpen(!uploadOpen)}><Plus/> Upload</button>}</div>
      {uploadOpen&&<form className="meeting-document-form" onSubmit={uploadDocument}><label>Title<input required value={document.title} onChange={e=>setDocument({...document,title:e.target.value})}/></label><label>Local file <small>Required · max 25 MB</small><input required type="file" onChange={e=>setDocument({...document,file:e.target.files?.[0]||null})}/></label><label>SharePoint link <small>Optional</small><input type="url" placeholder="https://...sharepoint.com/..." value={document.sharepoint_url} onChange={e=>setDocument({...document,sharepoint_url:e.target.value})}/></label><div className="modal-fields"><label>Type<select value={document.document_type} onChange={e=>setDocument({...document,document_type:e.target.value})}>{["Meeting Brief","Proposal","Delivery","Research","Other"].map(value=><option key={value}>{value}</option>)}</select></label><label>Owner<input value={document.owner} onChange={e=>setDocument({...document,owner:e.target.value})}/></label></div><label>Tags <small>Comma separated</small><input value={document.tags} onChange={e=>setDocument({...document,tags:e.target.value})} placeholder="AI, Data, Risk"/></label><label>Description<textarea rows="2" value={document.description} onChange={e=>setDocument({...document,description:e.target.value})}/></label><div className="form-actions"><button type="button" onClick={()=>setUploadOpen(false)}>Cancel</button><button className="primary-action" disabled={saving||!document.file}>{saving?"Uploading…":"Upload"}</button></div></form>}
      <div className="meeting-document-list">{documents.map(item=><article key={item.id}><FileText/><span><b>{item.title}</b><small>{item.file_name||item.document_type}</small><TagList tags={item.tags}/></span><div>{item.stored_name&&<a href={api.documentDownloadUrl(item.id)} title="Download local copy"><Download/></a>}{(item.sharepoint_url||item.url)&&<a href={item.sharepoint_url||item.url} target="_blank" rel="noreferrer" title="Open SharePoint"><ExternalLink/></a>}{canWrite&&<button onClick={()=>removeDocument(item.id)} title="Remove"><Trash2/></button>}</div></article>)}</div>
      {!documents.length&&!uploadOpen&&<p className="empty-note">No documents uploaded for this meeting.</p>}{documentError&&<p className="modal-error">{documentError}</p>}
    </div>
    <div className="brief-actions"><button className="primary" onClick={copyBrief}>{copied?"Brief copied":"Copy meeting brief"}</button>{person&&<button onClick={()=>onStakeholder(person)}>View stakeholder</button>}</div></aside></div>;
}

function TaskModal({pod,people,opportunities,owners,currentEmployeeId,currentUserName,onClose,onCreated}) {
  const defaultOwner=owners.find(item=>item.id===currentEmployeeId)||owners[0]||{id:currentEmployeeId||"",name:currentUserName||"Account team"};
  const [draft,setDraft]=useState({title:"",ownerEmployeeId:defaultOwner.id||"",owner:defaultOwner.name,due:todayKey(),priority:"Medium",stakeholder:"",opportunity:"",tags:""}); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
  const submit=async e=>{e.preventDefault();setSaving(true);setError("");try{const task=await api.createPodTask(pod,{title:draft.title,owner:draft.owner,owner_employee_id:draft.ownerEmployeeId||null,due:draft.due,priority:draft.priority,stakeholder_id:draft.stakeholder||null,opportunity_id:draft.opportunity||null,tags:draft.tags.split(",").map(value=>value.trim()).filter(Boolean)});onCreated(task);onClose();}catch(err){setError(err.message)}finally{setSaving(false)}};
  return <div className="pod-drawer-backdrop modal-layer"><form className="pod-modal" role="dialog" aria-modal="true" aria-labelledby="task-dialog-title" onSubmit={submit}><button type="button" className="pod-detail-close" onClick={onClose} aria-label="Close"><X/></button><div className="detail-kicker"><ListChecks/> NEW ACTION</div><h2 id="task-dialog-title">Add account task</h2><label>Action<input required autoFocus value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><div className="modal-fields"><label>Owner<SearchableSelect ariaLabel="Owner" value={draft.ownerEmployeeId} onChange={value=>{const owner=owners.find(item=>item.id===value);setDraft({...draft,ownerEmployeeId:value,owner:owner?.name||"Account team"})}} options={owners}/></label><label>Priority<select value={draft.priority} onChange={e=>setDraft({...draft,priority:e.target.value})}><option>High</option><option>Medium</option><option>Low</option></select></label></div><label>Due date<input type="date" required value={draft.due} onChange={e=>setDraft({...draft,due:e.target.value})}/></label><label>Linked stakeholder<SearchableSelect ariaLabel="Linked stakeholder" value={draft.stakeholder} onChange={value=>setDraft({...draft,stakeholder:value})} options={people} allowClear placeholder="Not linked"/></label><label>Linked opportunity<AdaptiveSelect value={draft.opportunity} onChange={value=>setDraft({...draft,opportunity:value})} options={opportunities} allowClear/></label><label>Tags <small>Comma separated</small><input value={draft.tags} onChange={e=>setDraft({...draft,tags:e.target.value})} placeholder="AI, Data, Risk"/></label>{error&&<p className="modal-error">Unable to save this action. Check the API and try again.</p>}<div className="form-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary-action" disabled={saving}>{saving?"Saving…":"Add task"}</button></div></form></div>;
}

function OpportunityDrawer({item,onClose,onStakeholder}) { return <div className="pod-drawer-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><aside className="pod-detail" role="dialog" aria-modal="true" aria-label={`${item.name} opportunity`}><button className="pod-detail-close" onClick={onClose} aria-label="Close"><X/></button><div className="detail-kicker"><CircleDollarSign/> OPPORTUNITY</div><h2>{item.name}</h2><p className="detail-time">Target close · {item.close}</p><div className="opportunity-hero"><strong>{money(item.value)}</strong><span>{item.probability}% probability</span><em>{item.stage}</em></div><dl><dt>Buyer / sponsor</dt><dd>{item.buyer}</dd><dt>Capco owner</dt><dd>{item.owner||"Account team"}</dd><dt>Weighted value</dt><dd>{money(item.value*item.probability/100)}</dd><dt>Latest movement</dt><dd>{item.movement}</dd></dl><h3>Opportunity context</h3><p>{item.description||"Opportunity aligned to the stakeholder's transformation priorities and next decision point."}</p><h3>Recommended next step</h3><p>{item.nextStep||"Confirm the decision path, commercial owner, and next client commitment before the target close date."}</p><div className="brief-actions"><button className="primary" onClick={()=>onStakeholder({id:item.stakeholderId,name:item.buyer})}>View stakeholder</button><button onClick={onClose}>Close</button></div></aside></div> }

function FocusModal({pod,focus,onClose,onSaved}) {
  const [items,setItems]=useState(focus); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
  const submit=async e=>{e.preventDefault();setSaving(true);setError("");try{const result=await api.updatePodFocus(pod,items.filter(Boolean));onSaved(result.focus);onClose()}catch{setError("Priorities could not be saved. Try again.")}finally{setSaving(false)}};
  return <div className="pod-drawer-backdrop modal-layer"><form className="pod-modal" role="dialog" aria-modal="true" aria-labelledby="focus-dialog-title" onSubmit={submit}><button type="button" className="pod-detail-close" onClick={onClose} aria-label="Close"><X/></button><div className="detail-kicker"><Target/> LEADERSHIP FOCUS</div><h2 id="focus-dialog-title">Edit monthly priorities</h2>{items.map((x,i)=><label key={i}>Priority {i+1}<input required value={x} onChange={e=>setItems(items.map((v,n)=>n===i?e.target.value:v))}/></label>)}{error&&<p className="modal-error">{error}</p>}<div className="form-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary-action" disabled={saving}>{saving?"Saving…":"Save priorities"}</button></div></form></div>
}

function StaffingPopover({resourcing,summary,onClose,onOpenResourcing}) {
  React.useEffect(()=>{const onKeyDown=event=>event.key==="Escape"&&onClose();document.addEventListener("keydown",onKeyDown);return()=>document.removeEventListener("keydown",onKeyDown)},[onClose]);
  const critical=summary?.criticalItems?.[0];
  const nextStart=summary?.startingSoon?.[0];
  return <div className="pod-drawer-backdrop pod-staffing-backdrop" onMouseDown={event=>event.target===event.currentTarget&&onClose()}>
    <aside className="pod-staffing-panel" role="dialog" aria-modal="true" aria-labelledby="staffing-panel-title">
      <header><div className="staffing-panel-mark"><UsersRound/></div><div><span>TALENT LIFECYCLE</span><h2 id="staffing-panel-title">Staffing overview</h2><p>Current demand and onboarding attention for this pod.</p></div><button autoFocus onClick={onClose} aria-label="Close staffing overview"><X/></button></header>
      <div className="staffing-panel-metrics"><article><small>OPEN DEMAND</small><strong>{resourcing.open_demand||0}</strong><span>roles to staff</span></article><article><small>ONBOARDING</small><strong>{resourcing.onboarding||0}</strong><span>active records</span></article><article className={resourcing.blocked?"risk":""}><small>BLOCKED</small><strong>{resourcing.blocked||0}</strong><span>need attention</span></article></div>
      <div className="staffing-panel-signals"><article><span>PRIORITY ATTENTION</span><strong>{critical?.headline||"No critical staffing items"}</strong>{critical?.detail&&<small>{critical.detail}</small>}</article><article><span>NEXT EXPECTED START</span><strong>{nextStart?.name||"No start in the next 30 days"}</strong>{nextStart&&<small>{[nextStart.expected_start_date,nextStart.role].filter(Boolean).join(" · ")}</small>}</article></div>
      <footer><button onClick={onClose}>Close</button><button className="primary-action" onClick={()=>{onClose();onOpenResourcing()}}>Open resourcing workspace <ArrowRight/></button></footer>
    </aside>
  </div>;
}

export default function PodView({pod,onOpenStakeholder,onOpenResourcing,canWrite=true,currentEmployeeId="",currentUserName=""}) {
  const [mode,setMode]=useState(()=>new URLSearchParams(window.location.search).get("view")==="month"?"month":"week"); const [anchor,setAnchor]=useState(()=>new Date()); const [filter,setFilter]=useState("All"); const [tagFilter,setTagFilter]=useState("All"); const [selected,setSelected]=useState(null); const [dayDetail,setDayDetail]=useState(null); const [taskScope,setTaskScope]=useState("Mine"); const [taskSort,setTaskSort]=useState("Due date"); const [meetingScope,setMeetingScope]=useState("Mine"); const [data,setData]=useState(emptyDashboard); const [tasks,setTasks]=useState([]); const [apiState,setApiState]=useState("loading"); const [loadError,setLoadError]=useState(""); const [reloadKey,setReloadKey]=useState(0); const [taskOpen,setTaskOpen]=useState(false); const [focusOpen,setFocusOpen]=useState(false); const [staffingOpen,setStaffingOpen]=useState(false); const [selectedOpportunity,setSelectedOpportunity]=useState(null); const [notice,setNotice]=useState("");
  React.useEffect(()=>{
    let active=true; setApiState("loading"); setLoadError(""); setData(emptyDashboard()); setTasks([]); setSelected(null); setSelectedOpportunity(null);
    const start=mode==="week"?monday(anchor):monthStart(anchor); const key=`${start.getFullYear()}-${String(start.getMonth()+1).padStart(2,"0")}-${String(start.getDate()).padStart(2,"0")}`;
    api.getPodDashboard(pod,mode,key,tagFilter).then(payload=>{if(!active)return; if(payload.data_source!=="sql"||!payload.view_model) throw new Error("SQL dashboard payload unavailable"); setData(payload.view_model); setTasks(payload.view_model.tasks||[]); setApiState("sql");}).catch(()=>{if(!active)return;setApiState("offline");setLoadError("Pod View could not connect to the account database. Start the API on port 8000, then retry.")});
    return()=>{active=false};
  },[pod,mode,anchor,tagFilter,reloadKey]);
  React.useEffect(()=>{setTagFilter("All");setMeetingScope("Mine");setTaskScope("Mine")},[pod]);
  React.useEffect(()=>{setSelected(current=>current?(data.meetings.find(item=>item.id===current.id)||current):current)},[data]);
  const meetingDeepLinkHandled=React.useRef(false);
  React.useEffect(()=>{const meetingId=new URLSearchParams(window.location.search).get("meeting");if(!meetingDeepLinkHandled.current&&meetingId){const event=data.meetings.find(item=>item.id===meetingId);if(event){setSelected(event);meetingDeepLinkHandled.current=true}}},[data]);
  React.useEffect(()=>{if(!notice)return undefined;const timer=setTimeout(()=>setNotice(""),2800);return()=>clearTimeout(timer)},[notice]);
  const toggleTask = async (task) => {
    const next=task.status==="Done"?"Open":"Done";
    setTasks(xs=>xs.map(x=>x.id===task.id?{...x,status:next}:x));
    try { await api.updatePodTask(task.pod||pod,task.id,next); setApiState("sql"); setNotice(next==="Done"?"Action completed":"Action reopened"); setReloadKey(value=>value+1); }
    catch { setTasks(xs=>xs.map(x=>x.id===task.id?{...x,status:task.status}:x)); setApiState("offline"); setNotice("Change could not be saved"); }
  };
  const resolveCritical = async (item) => {
    setData(current=>({...current,criticalItems:current.criticalItems.filter(value=>value.id!==item.id),commitments:current.commitments.filter(value=>value.id!==item.id)}));
    try { await api.updateCriticalItem(item.pod||pod,item.id,"Resolved"); setApiState("sql"); setNotice("Critical item resolved"); setReloadKey(value=>value+1); }
    catch { setReloadKey(value=>value+1); setApiState("offline"); setNotice("Critical item could not be resolved"); }
  };
  const summary=data.summary||emptyDashboard().summary; const pipeline=summary.pipelineValue, weighted=summary.weightedPipelineValue; const asOf=data.health?.[0]?.asOf||todayKey(); const overdue=summary.overdueActionCount;
  const shift=(direction)=>setAnchor(d=>{const n=new Date(d); mode==="week"?n.setDate(n.getDate()+direction*7):n.setMonth(n.getMonth()+direction); return n;});
  const period=mode==="week"?`${shortDate(monday(anchor))} – ${shortDate(new Date(monday(anchor).getTime()+6*DAY))}, ${anchor.getFullYear()}`:longMonth(anchor);
  const openPerson=async(reference)=>{const id=typeof reference==="object"?reference?.id:reference;if(!id||await onOpenStakeholder({id})===false){setNotice("The linked database stakeholder could not be loaded");return false}return true};
  const taskPriority={High:0,Medium:1,Low:2};
  const isCurrentUser=(employeeId,name)=>Boolean(currentEmployeeId&&employeeId===currentEmployeeId)||Boolean(currentUserName&&name===currentUserName);
  const visibleTasks=tasks.filter(t=>taskScope==="Mine"?isCurrentUser(t.ownerEmployeeId,t.owner):taskScope==="Pod Team"?t.status!=="Done":true).sort((a,b)=>(a.status==="Done")-(b.status==="Done")||(taskSort==="Priority"?(taskPriority[a.priority]??9)-(taskPriority[b.priority]??9):taskSort==="Owner"?(a.owner||"").localeCompare(b.owner||""):(a.due||"9999").localeCompare(b.due||"9999")));
  const visiblePrep=(data.upcomingPrep||[]).filter(e=>meetingScope==="Mine"?(e.capcoAttendeeIds||[]).includes(currentEmployeeId)||(e.capcoAttendees||[]).includes(currentUserName):meetingScope==="Pod Team"?(e.capcoAttendees||[]).length>0:true);
  const highRelationships=summary.highRelationshipAttentionCount; const taskOwners=[...new Map(tasks.filter(t=>t.owner).map(t=>[t.ownerEmployeeId||t.owner,{id:t.ownerEmployeeId||"",name:t.owner}])).values()];
  if(currentEmployeeId&&currentUserName&&!taskOwners.some(item=>item.id===currentEmployeeId))taskOwners.unshift({id:currentEmployeeId,name:currentUserName});
  const pulse=[{label:`${summary.meetingCount} Meetings`,sub:`${summary.buyerCount} Buyers · ${summary.influencerCount} Influencers`,icon:CalendarDays},{label:`${summary.deadlineCount} Deadlines`,sub:`${summary.urgentDeadlineCount} critical / high priority`,icon:Flag},{label:`${summary.openActionCount} Actions Due`,sub:`${summary.overdueActionCount} Overdue`,icon:ListChecks},{label:`${money(summary.pipelineValue)} Pipeline`,sub:`${money(summary.weightedPipelineValue)} weighted`,icon:CircleDollarSign},{label:`${summary.relationshipAttentionCount} Need Attention`,sub:`${summary.highRelationshipAttentionCount} high priority`,icon:UsersRound}];
  if(loadError)return <div className="pod-view"><div className="pod-view-head"><div><span>{pod.toUpperCase()} POD VIEW</span><h1>Morgan Stanley Account Intelligence</h1><p>Canonical account data <i className="data-status offline">Database unavailable</i></p></div></div><div className="pod-database-error"><AlertTriangle/><h2>Account database unavailable</h2><p>{loadError}</p><button onClick={()=>setReloadKey(value=>value+1)}>Retry connection</button></div></div>;
  return <div className="pod-view"><div className="pod-view-head"><div><span>{pod.toUpperCase()} POD VIEW</span><h1>Morgan Stanley Account Intelligence</h1><p>{mode==="week"?"Tactical priorities, client moments and deadlines":"Strategic account movement, coverage and monthly outcomes"} <i className={`data-status ${apiState}`}>{apiState==="sql"?"Live SQL data":"Refreshing…"}</i></p></div><div className="pod-view-controls"><label className="pod-tag-filter"><Tag/><span>Account tag</span><select value={tagFilter} onChange={e=>setTagFilter(e.target.value)}><option>All</option>{data.tagOptions.map(value=><option key={value}>{value}</option>)}</select></label><div className="period-controls"><button onClick={()=>shift(-1)} aria-label="Previous period"><ChevronLeft/></button><strong>{period}</strong><button onClick={()=>shift(1)} aria-label="Next period"><ChevronRight/></button><button className="today-button" onClick={()=>setAnchor(new Date())}>Today</button><div className="period-toggle"><button className={mode==="week"?"active":""} onClick={()=>setMode("week")}>Week</button><button className={mode==="month"?"active":""} onClick={()=>setMode("month")}>Month</button></div></div></div></div>
    <div className="pod-pulse" aria-label="Pod pulse">{pulse.map(({label,sub,icon:Icon})=><div className="pulse-metric" key={label}><Icon/><span><b>{label}</b><small>{sub}</small></span></div>)}</div>
    <div className="pod-scroll">
      {data.resourcing&&<button className="pod-staffing-summary" onClick={()=>setStaffingOpen(true)} aria-haspopup="dialog"><span className="staffing-summary-title"><UsersRound/><i><b>Staffing</b><small>Talent lifecycle</small></i></span><span className="staffing-summary-metric"><small>OPEN</small><b>{data.resourcing.open_demand||0}</b></span><span className={`staffing-summary-metric ${data.resourcing.blocked?"risk":""}`}><small>BLOCKED</small><b>{data.resourcing.blocked||0}</b></span><span className="staffing-summary-action">View details <ChevronRight/></span></button>}
      {mode==="week"&&<div className="pod-priority-bar"><Target/><b>Leadership focus</b>{data.focus.map((item,index)=><span key={item}>{index+1}. {item}</span>)}</div>}
      <div className="pod-primary-grid">
        <Section className="calendar-card" title={mode==="week"?"Week calendar":"Month calendar"} meta={mode==="week"?"Account-aware schedule · Eastern time":"Meetings, deadlines and milestones"} action={<div className="calendar-filters">{["All","Client","Internal","Deadlines"].map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div>}><div id="pod-calendar">{mode==="week"?<WeekCalendar anchor={anchor} events={data.meetings} filter={filter} onEvent={setSelected}/>:<MonthCalendar anchor={anchor} events={data.meetings} milestones={data.milestones} onEvent={setSelected} onDay={setDayDetail}/>}</div></Section>
        {mode==="week"?<Section title="Upcoming & meeting prep" meta={`${visiblePrep.length} upcoming · grounded AI brief available for every meeting`} action={<div className="scope-toggle">{["Mine","Pod Team","All"].map(x=><button className={meetingScope===x?"active":""} onClick={()=>setMeetingScope(x)} key={x}>{x}</button>)}</div>}><div className="prep-list">{!visiblePrep.length&&<EmptyState>No upcoming meetings match this view</EmptyState>}{visiblePrep.map(e=><button key={`${e.pod}-${e.id}`} onClick={()=>setSelected(e)}><span className="date-tile"><b>{new Date(e.start).getDate()}</b><small>{new Date(e.start).toLocaleDateString("en-US",{month:"short"}).toUpperCase()}</small></span><span><b>{e.title}</b><small>{time(e.start)} · {e.person}{pod==="All"?` · ${e.pod}`:""}</small><em>Capco: {(e.capcoAttendees||[]).join(", ")}</em><TagList tags={e.tags}/></span><span className="prep-chip ai-ready"><Sparkles/> AI brief</span><ChevronRight/></button>)}</div></Section>:<Section className="focus-card" title="Monthly leadership focus" meta="Priorities for the selected period" action={canWrite&&pod!=="All"&&<button className="text-action" onClick={()=>setFocusOpen(true)}>Edit</button>}><ol>{data.focus.map((x,i)=><li key={x}><span>{String(i+1).padStart(2,"0")}</span><b>{x}</b></li>)}</ol><div className="month-stat"><TrendingUp/><span><b>{money(weighted)}</b><small>weighted pipeline</small></span></div><div className="month-stat"><UsersRound/><span><b>{highRelationships} priority relationships</b><small>calculated from meeting recency</small></span></div></Section>}
      </div>
      {mode==="week"&&<div className="pod-two-col"><Section className="commitments-card" title="Upcoming deadlines" meta="One deadline format · earliest due first" action={<span className="section-count">{summary.deadlineCount} deadlines</span>}><CommitmentList items={data.commitments} pod={pod} onPerson={openPerson} onResolve={resolveCritical} canWrite={canWrite}/></Section><Section title="Actions & to-dos" meta={`${overdue} overdue · ${tasks.filter(t=>t.status!=="Done").length} open · ${visibleTasks.length} shown`} action={<div className="workload-controls"><div className="scope-toggle">{["Mine","Pod Team","All"].map(x=><button className={taskScope===x?"active":""} onClick={()=>setTaskScope(x)} key={x}>{x}</button>)}</div><label>Sort<select value={taskSort} onChange={e=>setTaskSort(e.target.value)}><option>Due date</option><option>Priority</option><option>Owner</option></select></label>{canWrite&&pod!=="All"&&<button className="add-task" onClick={()=>setTaskOpen(true)}><Plus/> Add</button>}</div>}><div id="pod-actions" className="task-list">{!visibleTasks.length&&<EmptyState>No actions match this filter</EmptyState>}{visibleTasks.map(t=><div key={`${t.pod}-${t.id}`} className={`${t.status==="Done"?"done":""} ${t.due&&t.due<asOf?"overdue":""}`}><button disabled={!canWrite} onClick={()=>toggleTask(t)} aria-label={`${t.status==="Done"?"Reopen":"Complete"} ${t.title}`}>{t.status==="Done"?<Check/>:null}</button><span><b>{t.title}</b><small>{t.owner} · {t.stakeholder||"Account"}{pod==="All"?` · ${t.pod}`:""}</small><TagList tags={t.tags}/></span><em>{t.due&&t.due<asOf?"Overdue":t.due?new Date(`${t.due}T12:00:00`).toLocaleDateString("en-US",{month:"short",day:"numeric"}):"No date"}</em></div>)}</div></Section></div>}
      <div className="pod-two-col"><Section title={mode==="week"?"Commercial pipeline":"Pipeline movement"} meta={`${money(pipeline)} pipeline · ${money(weighted)} weighted`}><div id="pod-pipeline" className="pipeline-list">{data.opportunities.map(o=><button key={`${o.pod}-${o.id}`} onClick={()=>setSelectedOpportunity(o)}><span><b>{o.name}</b><small>{o.buyer} · {o.close}{pod==="All"?` · ${o.pod}`:""}</small><TagList tags={o.tags}/></span><span><strong>{money(o.value)}</strong><em>{o.probability}% · {o.stage}</em></span><i style={{"--progress":`${o.probability}%`}}/><small className="movement"><TrendingUp/> {o.movement}</small></button>)}</div></Section><Section title={mode==="week"?"Relationship attention":"Relationship trend"} meta="No meeting first · then oldest last meeting"><RelationshipAttention items={data.relationshipAttention||[]} pod={pod} onPerson={openPerson}/></Section></div>
      {mode==="month"&&<div className="pod-lower-single"><Section className="commitments-card" title="Upcoming deadlines" meta="One deadline format · earliest due first" action={<span className="section-count">{summary.deadlineCount} deadlines</span>}><CommitmentList items={data.commitments} pod={pod} onPerson={openPerson} onResolve={resolveCritical} canWrite={canWrite}/></Section></div>}
      <Section className="health-card" title="Delivery & account health" meta="Calculated live from the currently filtered SQL records"><div className="health-grid">{data.health.map(h=><article key={h.label}><header><b>{h.label}</b><span className={h.status.toLowerCase()}>{h.status}</span></header><strong>{h.value}<small>/100</small></strong><div><i style={{width:`${h.value}%`}}/></div><p>{h.detail}</p><small className="health-formula">{h.formula}</small></article>)}</div></Section>
    </div>
    {selected&&<MeetingDrawer event={selected} people={data.people} opportunity={data.opportunities.find(o=>o.id===selected.opportunityId)} canWrite={canWrite} onClose={()=>setSelected(null)} onStakeholder={async p=>{if(await openPerson(p))setSelected(null)}} onOpportunity={item=>{setSelected(null);setSelectedOpportunity(item)}}/>}
    {dayDetail&&<div className="pod-drawer-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setDayDetail(null)}><aside className="pod-detail day-detail"><button className="pod-detail-close" onClick={()=>setDayDetail(null)}><X/></button><div className="detail-kicker"><CalendarDays/> DAY AGENDA</div><h2>{dayDetail.day.toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric"})}</h2>{dayDetail.items.length||dayDetail.milestones.length?<div className="day-agenda">{dayDetail.items.map(e=><button key={e.id} onClick={()=>{setDayDetail(null);setSelected(e)}}><b>{time(e.start)}</b><span><strong>{e.title}</strong><small>{e.person}</small></span><ChevronRight/></button>)}{dayDetail.milestones.map(m=><button key={m.title}><Flag/><span><strong>{m.title}</strong><small>{m.type} · {m.owner}</small></span></button>)}</div>:<p className="empty-day">No account events scheduled.</p>}</aside></div>}
    {taskOpen&&<TaskModal pod={pod} people={data.people} opportunities={data.opportunities} owners={taskOwners} currentEmployeeId={currentEmployeeId} currentUserName={currentUserName} onClose={()=>setTaskOpen(false)} onCreated={task=>{setTasks(xs=>[...xs,task]);setNotice("Action added")}}/>}
    {focusOpen&&<FocusModal pod={pod} focus={data.focus} onClose={()=>setFocusOpen(false)} onSaved={focus=>{setData(current=>({...current,focus}));setNotice("Leadership priorities saved")}}/>} 
    {staffingOpen&&data.resourcing&&<StaffingPopover resourcing={data.resourcing} summary={data.resourcingSummary} onClose={()=>setStaffingOpen(false)} onOpenResourcing={onOpenResourcing}/>}
    {selectedOpportunity&&<OpportunityDrawer item={selectedOpportunity} onClose={()=>setSelectedOpportunity(null)} onStakeholder={async person=>{if(await openPerson(person))setSelectedOpportunity(null)}}/>}
    {notice&&<div className="pod-toast" role="status"><Check/>{notice}</div>}
  </div>;
}
